apiVersion: v1
kind: PersistentVolume
metadata:
  name: tomcat-pv 
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: "disk-for-k8s-volume"
    fsType: ext4